# Generated by Django 5.2 on 2025-04-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_attendancerecord_students_subjects_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='branch',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
